### ISSUE TITLE
APP TOO OLD

### ISSUE THREAD

**Issue by Havivw** [ElectronicCats/flipper-SX1262-LoRa#1]
Hi, 
Got APP:54 < FW:66
This app might not work.

Momentum Firmware: mntm-dev-ec642d7c

**Comment by xpeqex** [comment]
Hello @Havivw 

Thank you for bringing this to our attention and the feedback. We will work to update the app to newer versions. For now and as stated here: [Flipper LoRa Relay-Requirements](https://github.com/ElectronicCats/flipper-SX1262-LoRa/wiki/1.-First-Steps-Flipper-LoRa-Relay-app#requirements) we recommend use Unleashed 071 or the version that is compatible with the firmware you are using. 

Hope you find it helpful. Feel free to open a new issue if there are any other queries!

**Comment by sabas1080** [comment]
App too OLD
APP54 < FW:69
With Unleashed firmware 69

**Comment by sabas1080** [comment]
Fix in new release https://github.com/ElectronicCats/flipper-SX1262-LoRa/releases/tag/v1.1.2.0
