### ISSUE TITLE
Compile Issues against latest dev branch

### ISSUE THREAD

**Issue by RogueMaster** [ElectronicCats/flipper-SX1262-LoRa#2]
Please check compilation against latest flipper dev branch for build errors.

u_int8_t being one of the errors, also date time fixes...

**Comment by xpeqex** [comment]
Hello @RogueMaster 

The dev branch is currently not in use for developing and/or testing. We invite you to use the [main](https://github.com/ElectronicCats/flipper-SX1262-LoRa/tree/main) branch instead. 

If you face any issue, please let us know!

**Comment by RogueMaster** [comment]
Please let me know when this app is developed for the dev branch, I've heard of considerable demand for flipper/lora support

**Comment by sabas1080** [comment]
@RogueMaster check the new release please https://github.com/ElectronicCats/flipper-SX1262-LoRa/releases/tag/v1.1.2.0

**Comment by RogueMaster** [comment]
Still has issues from old refactoring of DateTime on lora app... and u_int8_t on lora relay

**Comment by RogueMaster** [comment]
On new branch, lora_app builds after date time fixes

**Comment by RogueMaster** [comment]
Lora Relay still has these issues:


        CC      build\f7-firmware-C\.extapps\lora_relay\lora_relay_icons.c
applications\external\lora_relay\lora.c:780:24: error: unknown type name 'u_int8_t'; did you mean 'uint8_t'?
  780 | int lora_receive_async(u_int8_t* buff, int buffMaxLen) {
      |                        ^~~~~~~~
      |                        uint8_t
applications\external\lora_relay\view_lora_rx.c:18:24: error: unknown type name 'u_int8_t'; did you mean 'uint8_t'?
   18 | int lora_receive_async(u_int8_t* buff, int buffMaxLen);
      |                        ^~~~~~~~
      |                        uint8_t
applications\external\lora_relay\view_lora_rx.c: In function 'view_lora_rx_draw_callback_move':
applications\external\lora_relay\view_lora_rx.c:77:21: error: implicit declaration of function 'lora_receive_async' [-Werror=implicit-function-declaration]
   77 |     int bytesRead = lora_receive_async(receiveBuff, sizeof(receiveBuff));
      |                     ^~~~~~~~~~~~~~~~~~
cc1.exe: all warnings being treated as errors
applications\external\lora_relay\lora_relay.c:37:24: error: unknown type name 'u_int8_t'; did you mean 'uint8_t'?
   37 | int lora_receive_async(u_int8_t* buff, int buffMaxLen);
      |                        ^~~~~~~~
      |                        uint8_t

**Comment by RogueMaster** [comment]
I can now build the two on my FW, can you explain the difference between the two?

**Comment by sabas1080** [comment]
@RogueMaster fixed in new release

**Comment by RogueMaster** [comment]
Thank you, your three apps are now included in RM firmware

**Comment by sabas1080** [comment]
@RogueMaster thank you for your feedback!
